### ISSUE TITLE
What would be the code to Terminate the main thread but not the process?

### ISSUE THREAD

**Issue by michel529020** [effetdoppler/Thread#3]
https://github.com/effetdoppler/Thread/blob/bdf3c5d0f7cf2eda9f566024acad47c3e4a4e9ad/basics/hello.c#L44

**Comment by effetdoppler** [comment]
int main(int argc, char** argv)
{
    // Check the number of arguments.
    if (argc < 2)
        errx(EXIT_FAILURE, "The number of threads is missing.");
    else if (argc > 2)
        errx(EXIT_FAILURE, "Specify only the number of threads.");

    // - Convert the argument into a long integer.
    //   Use atol(3).
    //   This value represents the number of threads.
    long nb = atol(argv[1]);
    // - If the argument is not valid (i.e. lower than or equal to zero),
    //   exit with an error message.
    if (nb <= 0)
        errx(EXIT_FAILURE, "The number of threads is not valid.");
    // - Create and execute the threads.
    int e;
    pthread_t thr[nb];
    for (long i = 0; i < nb; i++)
    {
        e = pthread_create(&thr+i, NULL, fn_thread, NULL);
        //   If an error occurs, exit with an error message.
        //   You can use err(3), but the 'errno' variable is not set automatically.
        //   You have to set it manually to the return value of pthread_create().
        if (e!=0)
        {
            errno = e;
            err(EXIT_FAILURE, "pthread_create(): %s");
        }
    }
    
   
    // - Finally, there are two possibilities to terminate the main thread :
    //   1. Wait for all the other threads to end.
    //      Return from the function (terminate the process).
    
    //   2. Do not wait for the other threads.
    //      Terminate the main thread but not the process.
    //   (The two possibilites are right.)
    pthread_exit(NULL);
}

**Comment by michel529020** [comment]
Great
